name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Deploy apenas quando mudanças forem enviadas à branch main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag gcr.io/${{ secrets.GCP_PROJECT }}/shorten-api:latest \
          --push \
          .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy shorten-api \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/shorten-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars REDIS_HOST=your-redis-host REDIS_PORT=your-redis-port

